local_costmap:
  global_frame: /odom_combined
  robot_base_frame: /base_footprint
  update_frequency: 10.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05