<?xml version="1.0"?>
<robot 
    xmlns:xacro="http://www.ros.org/wiki/xacro"
    name="automow">

    <material name="Green">
        <color rgba="0.0 0.8 0.0 1.0"/>
    </material>
    <material name="Red">
        <color rgba="0.8 0.0 0.0 1.0"/>
    </material>
    <material name="White">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>
    <material name="Blue">
        <color rgba="0.0 0.0 0.8 1.0"/>
    </material>
    <material name="Black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>
    <material name="Grey">
        <color rgba="0.7 0.7 0.7 0.7"/>
    </material>

    <xacro:property name="M_PI" value="3.14159"/>

    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                     iyy="1.0" iyz="0.0"
                     izz="1.0" />
        </inertial>
    </xacro:macro>

    <!-- base_footprint is a ficticious frame on the ground below base_link
     for the navigation stack to properly function -->
    <link name="base_footprint">
        <inertial>
        <mass value="0.0001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001" />
        </inertial>

        <visual>
         <origin xyz="0 0 0" rpy="0 0 0" />
         <geometry>
             <box size="0.001 0.001 0.001" />
         </geometry>
         <material name="Green" />
        </visual>

        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
         <geometry>
             <box size="0.001 0.001 0.001" />
         </geometry>
        </collision>
    </link>

    <!-- base_link is the origin for all of the coordinates on the robot.
      For our case, this will be centered under the wheels of the
      robot. -->
    <xacro:property name="clearance" value="0.065" />
    <xacro:property name="c_width" value="0.51" />
    <xacro:property name="c_length" value="0.73" />
    <xacro:property name="c_height" value="0.54" />

    <xacro:property name="c1_length" value="0.515" />
    <xacro:property name="c1_height" value="0.27" />

    <xacro:property name="c2_length" value="0.515" />
    <xacro:property name="c2_height" value="0.27"/>


    <link name="base_link">
        <xacro:default_inertial mass="100"/>
        <visual>
            <origin xyz="${c1_length/2 - 0.215} 0 ${c1_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${c1_length} ${c_width} ${c1_height}" />
            </geometry>
            <material name="Grey" />
        </visual>
    
        <collision>
            <origin xyz="${c1_length/2 - 0.215} 0 ${c1_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${c1_length} ${c_width} ${c1_height}" />
            </geometry>
        </collision>
    </link>

    <link name="base_top">
        <visual>
            <origin xyz="${c2_length/2} 0 -${c2_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${c2_length} ${c_width} ${c2_height}" />
            </geometry>
            <material name="Grey" />
        </visual>
        <collision>
            <origin xyz="${c2_length/2} 0 -${c2_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${c2_length} ${c_width} ${c2_height}" />
            </geometry>
        </collision>
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${clearance}" rpy="0 0 0"/>
        <parent link="base_footprint"/>
        <child link="base_link"/>
    </joint>

    <joint name="base_top_joint" type="fixed">
        <origin xyz="0 0 ${c_height}" />
        <parent link="base_link"/>
        <child link="base_top"/>
    </joint>

    <xacro:property name="wheeldiam" value="0.27"/>

    <xacro:macro name="wheel" params="prefix reflect">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheeldiam/2}" length="0.1"/>
                </geometry>
                <material name="Black"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheeldiam/2}" length="0.1"/>
                </geometry>
            </collision>
            <xacro:default_inertial mass="1"/>
        </link>
        <joint name="${prefix}_wheel_joint" type="fixed">
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <origin xyz="0 ${(c_width/2 + 0.05)*reflect} ${wheeldiam/2 - clearance}"
                rpy="${M_PI/2} 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:wheel prefix="left" reflect="1"/>
    <xacro:wheel prefix="right" reflect="-1"/>

    <xacro:property name="d_width" value=".775"/>
    <xacro:property name="d_length" value=".385"/>
    <xacro:property name="d_height" value=".085"/>

    <link name="deck_link">
        <visual>
            <origin xyz="0 0 -${d_height/2}"/>
            <geometry>
                <box size="${d_length} ${d_width} ${d_height}"/>
            </geometry>
            <material name="Blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${d_length} ${d_width} ${d_height}"/>
            </geometry>
        </collision>
    </link>

    <joint name="deck_joint" type="fixed">
        <parent link="base_link"/>
        <child link="deck_link"/>
        <origin xyz="${(.73 - .215 + .06)} 0 ${d_height}"/>
    </joint>

    <xacro:property name="blade_diameter" value="0.356"/>
    <xacro:macro name="cutter" params="prefix reflect">
        <link name="${prefix}_cutter">
            <visual>
                <origin xyz="0 0 -0.01"/>
                <geometry>
                    <cylinder radius="${blade_diameter/2}" length="0.02"/>
                </geometry>
                <material name="Green"/>
            </visual>
            <collision>
                <origin xyz="0 0 -0.01"/>
                <geometry>
                    <cylinder radius="${blade_diameter/2}" length="0.02"/>
                </geometry>
            </collision>
            <xacro:default_inertial mass="1"/>
        </link>
        <joint name="${prefix}_cutter_joint" type="fixed">
            <parent link="deck_link"/>
            <child link="${prefix}_cutter"/>
            <origin xyz="0 ${blade_diameter/2 * reflect} -0.08"/>
        </joint>
    </xacro:macro>

    <xacro:cutter prefix="left" reflect="1"/>
    <xacro:cutter prefix="right" reflect="-1"/>


    <link name="gps">
        <visual>
            <origin xyz="0 0 -0.01"/>
            <geometry>
                <cylinder radius="0.09" length="0.02"/>
            </geometry>
            <material name="White"/>
        </visual>
    </link>

    <joint name="gps_joint" type="fixed">
        <parent link="base_top"/>
        <child link="gps"/>
        <origin xyz="0 0 0.165"/>
    </joint>

    <link name="laser">
        <visual>
            <origin xyz="0 0 -0.02" />
            <geometry>
                <cylinder radius="0.06" length="0.08"/>
            </geometry>
            <material name="Red"/>
        </visual>
        <collision>
            <origin xyz="0 0 -0.02" />
            <geometry>
                <cylinder radius="0.06" length="0.08"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="0.5"/>
    </link>
    
    <link name="ahrs">
        <visual>
            <geometry>
                <box size="0.02 0.02 0.02"/>
            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.02 0.02 0.02"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="0.001"/>
    </link>

    <joint name="laser_joint" type="fixed">
        <origin xyz="0.815 0 0.215" rpy="0 0 0"/>
        <parent link="base_link" />
        <child link="laser" />
    </joint>

    <joint name="ahrs_joint" type="fixed">
        <origin xyz="0.22 0 ${c_height - 0.02}" rpy="${M_PI} 0 0"/>
        <parent link="base_link" />
        <child link="ahrs" />
    </joint>

    <link name="kinect_link">
        <xacro:default_inertial mass="0.0001"/>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh
                  filename="package://automow_description/meshes/kinect.dae"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.0730 0.2760 0.0720"/>
            </geometry>
        </collision>
    </link>

    <link name="kinect_depth_frame">
        <xacro:default_inertial mass="0.000001"/>
    </link>

    <link name="kinect_depth_optical_frame">
        <xacro:default_inertial mass="0.000001"/>
    </link>

    <link name="kinect_rgb_frame">
        <xacro:default_inertial mass="0.000001"/>
    </link>

    <link name="kinect_rgb_optical_frame">
        <xacro:default_inertial mass="0.000001"/>
    </link>


    <joint name="base_kinect_joint" type="fixed">
        <origin xyz="0.49  0.005 ${c_height + 0.05}" rpy="0 ${M_PI/12} 0"/>
        <parent link="base_link"/>
        <child link="kinect_link"/>
    </joint>

    <joint name="kinect_depth_joint" type="fixed">
        <origin xyz="0 0.018 0" rpy="0 0 0" />
        <parent link="kinect_link" />
        <child link="kinect_depth_frame" />
    </joint>

    <joint name="kinect_depth_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${M_PI/2}"/>
        <parent link="kinect_depth_frame" />
        <child link="kinect_depth_optical_frame" />
    </joint>

    <joint name="kinect_rgb_joint" type="fixed">
      <origin xyz="0 -0.005 0" rpy="0 0 0" />
      <parent link="kinect_link" />
      <child link="kinect_rgb_frame" />
    </joint>

    <joint name="kinect_rgb_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${M_PI/2}"/>
      <parent link="kinect_rgb_frame" />
      <child link="kinect_rgb_optical_frame" />
    </joint>
</robot>




